---
title: "Enhancing scientific publishing through Quarto"
subtitle: UseR 2024
format: html
author: ""
date: ""
---

Quarto is the new generation of R Markdown for publishing dynamic and static documents, with multilingual support for programming languages. With Quarto, you can create documents, books, presentations, blogs and other online resources.

For this useR 2024 edition in Salzburg, a 3-hours tutorial introducing Quarto is being offered.

::: when-where
🗓️ Monday 8th July / 🕙 14h - 17h30 CEST
🏢 Wyndham Grand Salzburg conference centre - Room Pinzgau 
:::

# About Quarto

This tutorial will show you how Quarto reuses and rethinks the features of the R Markdown ecosystem, moving from several R packages to a single tool. 

Enhancing scientific publishing through Quarto is the workshop's focus, designed for those familiar with R Markdown and newcomers to Quarto. Quarto extends the foundational capabilities of R Markdown, introducing advanced features that elevate publishing projects. 

Quarto offers the reworked R Markdown functionalities (cross references, article layout, figure management, etc.) as well as multiple formats (HTML & PDF document, website, HTML presentation, etc.), and project management (Websites, Blogs, Books, ...) while adding new functionalities for greater flexibility and collaboration (easy modification of an HTML theme, extension mechanism, facilitated collaborative project, etc.).

- When and why should you switch from R Markdown to Quarto?
- How do you make the transition on existing projects?
- How do you start a new project with Quarto?
- When to use projects to organize your work and target enhanced publications ? 



# Getting ready

{{< fa book >}} [Documents to read](preparation.qmd) so that you are ready for the workshop and can use the examples and do the exercises.

# Schedule

::: schedule
-   {{< fa dna >}} Quarto: An evolution of R Markdown?

-   {{< fa recycle >}} How do I switch from R Markdown to Quarto?

-   {{< fa file >}} Produce quality documents with ease

-   {{< fa folder >}} Working with Quarto projects

-   {{< fa rocket >}} And much more...
:::

# Instructor

Christophe Dervieux is an open-Source sofware engineer at [Posit, PBC](https://posit.co/) working on projects in the R Markdown and Quarto ecosystems.

{{< include _license.qmd >}}
